-- Shared, public-read metadata cache. Only the service role may write.
CREATE TABLE IF NOT EXISTS public.media_metadata_cache (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  media_type text NOT NULL CHECK (media_type IN ('movie', 'tv')),
  source_title text NOT NULL,
  normalized_title text NOT NULL,
  release_year smallint NOT NULL DEFAULT 0 CHECK (release_year = 0 OR release_year BETWEEN 1900 AND 2099),
  language text NOT NULL CHECK (language IN ('bs-BA', 'de-DE')),
  tmdb_id bigint,
  data jsonb NOT NULL,
  fetched_at timestamptz NOT NULL DEFAULT now(),
  expires_at timestamptz NOT NULL DEFAULT (now() + interval '30 days'),
  UNIQUE (media_type, normalized_title, release_year, language)
);

CREATE INDEX IF NOT EXISTS media_metadata_cache_expires_at_idx
  ON public.media_metadata_cache (expires_at);

ALTER TABLE public.media_metadata_cache ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public read media metadata cache" ON public.media_metadata_cache;
CREATE POLICY "Public read media metadata cache"
  ON public.media_metadata_cache
  FOR SELECT
  TO anon, authenticated
  USING (true);

GRANT USAGE ON SCHEMA public TO anon, authenticated, service_role;
GRANT SELECT ON TABLE public.media_metadata_cache TO anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.media_metadata_cache TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.media_metadata_cache_id_seq TO service_role;

REVOKE INSERT, UPDATE, DELETE ON TABLE public.media_metadata_cache FROM anon, authenticated;

COMMENT ON TABLE public.media_metadata_cache IS
  'Shared TMDB metadata cache. Public clients may read; only service_role may refresh rows.';
